# Generated by Django 3.2.8 on 2021-11-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
