# Generated by Django 3.2.8 on 2021-11-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_maincontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='title',
            field=models.CharField(default=455, max_length=100),
            preserve_default=False,
        ),
    ]
