# Generated by Django 3.2.8 on 2021-11-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_maincontent_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincontent',
            old_name='content',
            new_name='main_content',
        ),
        migrations.RenameField(
            model_name='maincontent',
            old_name='title',
            new_name='main_title',
        ),
    ]
