# Generated by Django 3.2.8 on 2021-11-01 07:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_alter_maincontent_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintitle', models.CharField(max_length=100)),
                ('maincontent', ckeditor.fields.RichTextField()),
                ('featured', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
