# Generated by Django 3.2.8 on 2021-11-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_aboutsocial_socilcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutbulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletinTitle', models.TextField(blank=True, null=True)),
                ('bulletinLink', models.CharField(blank=True, max_length=200, null=True)),
                ('featured', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
