# Generated by Django 3.2.8 on 2021-12-13 20:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0013_footersocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintitle', models.CharField(blank=True, max_length=100, null=True)),
                ('maincontent', ckeditor.fields.RichTextField()),
                ('featured', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
