# Generated by Django 3.2.8 on 2021-12-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0015_alter_resume_maintitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='maincontent',
            new_name='resumecontent',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='maintitle',
            new_name='resumetitle',
        ),
    ]
