# Generated by Django 3.2.8 on 2021-12-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_auto_20211214_0242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
