# Generated by Django 3.2.8 on 2021-12-13 20:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_delete_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumetitle', models.CharField(max_length=100)),
                ('resumecontent', ckeditor.fields.RichTextField()),
                ('featured', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
