# Generated by Django 3.2.8 on 2021-10-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slider',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
